import type { City } from "@/content/types";

export const austinCities: City[] = [
  {
    slug: "austin",
    name: "Austin",
    region: "austin",
    county: "Travis",
    neighborhoods: ["Tarrytown", "Hyde Park", "Mueller", "Zilker", "Brentwood", "Allandale", "Travis Heights", "Northwest Hills"],
    zips: ["78703", "78704", "78702", "78731", "78757", "78745", "78748"],
    signature: "Austin’s long cooling season and older central homes without ductwork shape almost every job.",
    intro: "Central Austin still has bungalows and pier-and-beam houses in Hyde Park, Brentwood, Tarrytown, and Travis Heights where a full duct system was never part of the house. Farther out, Northwest Hills, South Austin, and Mueller are conventional systems fighting a cooling season that runs from April into October. Cedar pollen in winter makes air quality part of comfort, not a separate luxury.",
    housing: "Expect ductless retrofits in older central neighborhoods and attic or closet systems everywhere else. West Austin homes add glass, levels, and difficult equipment access.",
    climate: "Austin stays hot longer than Dallas and is milder in winter, but freezes still happen. Many homes are all-electric heat pumps rather than gas furnaces.",
    responseNote: "Central Austin, North Austin, and South Austin are scheduled as different routes.",
    nearby: ["round-rock", "pflugerville", "cedar-park", "lakeway", "bee-cave", "manor"],
    issues: [
      {
        title: "Bungalows that should not be torn up for ducts",
        body: "A Hyde Park or Clarksville house often cools better with ductless heads than with bulkheads and a new attic full of flex. We will recommend that when it is the smaller project.",
        tags: ["install", "cooling", "heating"],
      },
      {
        title: "Attic ducts in a very long cooling season",
        body: "South and North Austin houses with attic equipment run for months. Leaky flex shows up as rooms that never catch the thermostat and bills that do not match the setpoint.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "Cedar season and dusty returns",
        body: "From late fall into winter, Ashe juniper pollen loads filters and makes leaky returns worse. Indoor air work in Austin is seasonal, not theoretical.",
        tags: ["air", "maintenance"],
      },
    ],
  },
  {
    slug: "round-rock",
    name: "Round Rock",
    region: "austin",
    county: "Williamson",
    neighborhoods: ["Teravista", "Forest Creek", "Behrens Ranch", "Downtown Round Rock"],
    zips: ["78664", "78665", "78681"],
    signature: "Builder systems in Teravista, Forest Creek, and nearby sections are entering replacement age together.",
    intro: "Most Round Rock service is suburban: two-story houses, attic equipment, and the original builder system. Downtown Round Rock is older and occasionally needs a retrofit instead of a straight swap. The master-planned sections are where we see coils, compressors, and blower motors from the same building years failing in a cluster.",
    housing: "Production homes with flex duct in the attic are the default. Some older homes near downtown have smaller mechanical spaces.",
    climate: "Round Rock shares Austin’s long cooling season and adds a slightly colder winter north of the city.",
    responseNote: "Round Rock is grouped with Pflugerville, Hutto, and Georgetown.",
    nearby: ["pflugerville", "georgetown", "hutto", "austin", "cedar-park"],
    issues: [
      {
        title: "Matched builder systems aging out as a set",
        body: "If the condenser, coil, and air handler were installed together and one major component has failed, we price the repair and the replacement in the same visit so you can compare them.",
        tags: ["install", "cooling"],
      },
      {
        title: "Upstairs bedrooms at the end of long flex runs",
        body: "Forest Creek and Teravista plans often lose the rooms farthest from the air handler. That is a duct problem until measurement says otherwise.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "Heat pumps that have never had the backup tested",
        body: "A mild Austin winter hides a dead heat strip. Round Rock still gets nights cold enough to notice. We test backup heat on a maintenance visit.",
        tags: ["heating", "maintenance"],
      },
    ],
  },
  {
    slug: "cedar-park",
    name: "Cedar Park",
    region: "austin",
    county: "Williamson",
    neighborhoods: ["Buttercup Creek", "Anderson Mill", "Twin Creeks", "Ranch at Brushy Creek"],
    zips: ["78613"],
    signature: "Cedar Park two-stories with a single system often cannot keep the upstairs comfortable in July.",
    intro: "Anderson Mill has older houses and older equipment. Buttercup Creek and the newer sections are classic two-story production homes. The complaint is consistent: the thermostat downstairs is satisfied and the bedrooms are not. Sometimes the answer is duct correction. Sometimes the house really does need a second system.",
    housing: "Attic-mounted air handlers and flex duct are standard. Anderson Mill houses are more likely to be on a second or third condenser.",
    climate: "Cedar Park gets full Hill Country sun on west-facing glass and a cooling season that runs deep into fall.",
    responseNote: "Cedar Park is routed with Leander and northwest Austin.",
    nearby: ["leander", "austin", "round-rock", "georgetown"],
    issues: [
      {
        title: "Single systems asked to cover two floors",
        body: "We measure room temperatures and static pressure before we recommend a second system. Some Cedar Park houses need it. Some need the returns and a few supplies corrected.",
        tags: ["cooling", "ducts", "install"],
      },
      {
        title: "Older Anderson Mill equipment",
        body: "Repeat electrical failures on an aging condenser are a different job from a dirty coil. We will tell you which one you have.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Winter heat that is only electric strips",
        body: "If the heat pump is not running and the house is heating on strips alone, the bill shows it before the comfort does. We find out why the heat pump is sitting out.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "georgetown",
    name: "Georgetown",
    region: "austin",
    county: "Williamson",
    neighborhoods: ["Sun City", "Downtown Georgetown", "Berry Creek", "Serenada"],
    zips: ["78626", "78628", "78633"],
    signature: "Sun City homes and the older square downtown do not take the same equipment plan.",
    intro: "Georgetown has at least two housing markets. Sun City and neighboring active-adult sections have slab homes, specific equipment locations, and owners who keep maintenance records. The square and the older streets around it have houses that may need ductless or careful retrofits. West-side newer construction looks more like the rest of Williamson County.",
    housing: "Sun City mechanical closets and attic installs in Berry Creek are both common. Downtown houses are older and tighter.",
    climate: "Georgetown is hot and a step colder in winter than central Austin, which matters for heat pump backup.",
    responseNote: "Georgetown is its own northern route with Hutto and Round Rock, not a detour from central Austin.",
    nearby: ["round-rock", "hutto", "cedar-park", "leander"],
    issues: [
      {
        title: "Sun City systems with a long maintenance history",
        body: "These homes reward a technician who reads the past repairs. A repeat float-switch trip or a coil that has been cleaned twice is telling you something specific.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Downtown houses without a real duct plan",
        body: "Forcing a full duct system through an older Georgetown house can cost more and look worse than a ductless design. We price the option that fits the building.",
        tags: ["install", "cooling", "heating"],
      },
      {
        title: "Heat pump backup on colder Williamson nights",
        body: "Georgetown winters are mild until a front arrives. Backup heat that was never tested fails exactly then.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "pflugerville",
    name: "Pflugerville",
    region: "austin",
    county: "Travis",
    neighborhoods: ["Blackhawk", "Falcon Pointe", "Avalon", "Lake Pflugerville"],
    zips: ["78660"],
    signature: "Pflugerville’s newer houses often have kinked flex duct and returns that were never quite finished.",
    intro: "Pflugerville grew quickly, and the HVAC in that growth shows it. Blackhawk is older and closer to a normal replacement cycle. Falcon Pointe, Avalon, and the newer sections still have builder equipment, builder ducts, and builder shortcuts. A house can be only a few years old and cool poorly.",
    housing: "Production two-stories with attic flex are the main housing type. Mechanical permits and builder warranties still apply on the newest sections.",
    climate: "Pflugerville shares Austin’s long cooling season and the Blackland Prairie’s humidity.",
    responseNote: "Pflugerville is scheduled with Round Rock, Hutto, and East Austin.",
    nearby: ["round-rock", "austin", "hutto", "manor"],
    issues: [
      {
        title: "New houses with install defects",
        body: "Kinked flex, disconnected supplies, missing secondary drain protection, and thermostats that were never configured are all things we photograph. If a builder warranty applies, you should have that record.",
        tags: ["install", "ducts", "cooling"],
      },
      {
        title: "Blackhawk systems reaching mid-life",
        body: "The older Pflugerville sections are past the ‘brand new’ excuse. Capacitors, contactors, and dirty coils are maintenance. A failed compressor is a decision.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "All-electric heat that surprises people in January",
        body: "Many Pflugerville homes have no gas furnace. If the heat pump is down, the house is on expensive electric strips. We treat loss of heat as its own priority in a cold snap.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "leander",
    name: "Leander",
    region: "austin",
    county: "Williamson",
    neighborhoods: ["Crystal Falls", "Travisso", "Old Town Leander", "Bryson"],
    zips: ["78641"],
    signature: "Leander floor plans are big, and long flex-duct runs lose cooling before it reaches the far rooms.",
    intro: "Crystal Falls, Travisso, and Bryson are large-house markets. The equipment can be new and the back bedroom can still be wrong because the duct run is too long, too flat, or too small. Old Town Leander is a smaller, older housing stock with a more ordinary repair mix.",
    housing: "Multi-system houses are common in the master-planned sections. Heat pumps are more common than gas furnaces.",
    climate: "West of Round Rock, Leander gets strong afternoon sun and a cooling season that does not quit early.",
    responseNote: "Leander is routed with Cedar Park so a Crystal Falls visit is not paired with a Round Rock morning.",
    nearby: ["cedar-park", "georgetown", "round-rock"],
    issues: [
      {
        title: "Far rooms on long flex runs",
        body: "We measure supply temperature at the plenum and at the unhappy room. The difference tells us whether Leander ductwork is the job.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "New equipment with old-install habits",
        body: "A recent replacement that reused a bad line set location, a bad drain, or a bad return will misbehave immediately. We would rather fix the install than condemn the brand.",
        tags: ["install", "maintenance"],
      },
      {
        title: "Heat pumps in larger two-story plans",
        body: "Backup heat and defrost operation matter more in a big Leander house because a failure shows up as a whole floor, not one room.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "kyle",
    name: "Kyle",
    region: "austin",
    county: "Hays",
    neighborhoods: ["Plum Creek", "Waterleaf", "Kensington Trails", "Downtown Kyle"],
    zips: ["78640"],
    signature: "Kyle production homes are often undersized for west-facing glass and are hitting a first replacement cycle.",
    intro: "Kyle grew on production housing. Plum Creek is further along and has systems aging out of the builder years. Newer sections are still showing install quality problems: undersized returns, condensers in full afternoon sun, and thermostats that satisfy the room they are in while the rest of the house waits.",
    housing: "Two-story slab homes with attic equipment dominate. Downtown Kyle is smaller and older.",
    climate: "Hays County south of Austin is hot, bright, and less breezy than people expect once the houses are close together.",
    responseNote: "Kyle is scheduled with Buda and south Austin, not with Round Rock.",
    nearby: ["buda", "san-marcos", "austin"],
    issues: [
      {
        title: "West-facing glass the original load calc ignored",
        body: "A Kyle afternoon can overwhelm a system that looked fine on paper. We look at the glass and the ductwork before we add a half ton out of habit.",
        tags: ["cooling", "install"],
      },
      {
        title: "First-cycle replacements in Plum Creek",
        body: "Homeowners are choosing between a major repair and a new system on equipment that was never premium. We price both and include any duct corrections the new system would still need.",
        tags: ["install", "ducts"],
      },
      {
        title: "Filters and drains skipped in rental or new-owner homes",
        body: "A clogged primary drain in an attic air handler becomes a ceiling stain. Maintenance in Kyle is mostly unglamorous and worth it.",
        tags: ["maintenance", "air"],
      },
    ],
  },
  {
    slug: "buda",
    name: "Buda",
    region: "austin",
    county: "Hays",
    neighborhoods: ["Old Town Buda", "Garlic Creek", "Sunfield"],
    zips: ["78610"],
    signature: "Buda mixes older homes near downtown with brand-new sections that still have install defects.",
    intro: "Old Town Buda and the streets around it have houses that have been repaired for years. Sunfield and other new sections have equipment that should still be trouble-free and sometimes is not. We do not use a new-construction script on an older house, or the reverse.",
    housing: "Older homes may have smaller ducts and aging furnaces or air handlers. New sections are builder-grade attic systems.",
    climate: "Buda shares South Austin heat and Hays County’s bright western exposure.",
    responseNote: "Buda is paired with Kyle on the schedule.",
    nearby: ["kyle", "austin", "san-marcos", "dripping-springs"],
    issues: [
      {
        title: "Install defects in new sections",
        body: "Incorrect drainage, loose plenums, and registers that were never cut in cleanly show up in the first few summers. We document them.",
        tags: ["install", "cooling", "ducts"],
      },
      {
        title: "Older equipment worth repairing",
        body: "An older Buda system with one failed part and a clean coil is a repair. We will say that clearly.",
        tags: ["maintenance", "heating"],
      },
      {
        title: "Dust and attic return leaks",
        body: "If the return is pulling attic air, no filter brand will fix the dust. Sealing the return is the indoor air job that matters.",
        tags: ["air", "ducts"],
      },
    ],
  },
  {
    slug: "san-marcos",
    name: "San Marcos",
    region: "austin",
    county: "Hays",
    neighborhoods: ["Downtown San Marcos", "Blanco Vista", "Cottonwood Creek"],
    zips: ["78666"],
    signature: "Humidity near the river corridor makes moisture control as important as the thermostat number.",
    intro: "San Marcos has campus rentals, older houses, and newer subdivisions on the edges. River-corridor humidity means an oversized system can hit the setpoint and still leave the house damp. Rentals add deferred maintenance: filters, drains, and contactors that should have been replaced a year ago.",
    housing: "A mix of smaller older homes and standard suburban attic systems. Some rentals have been ‘repaired’ with the cheapest available part.",
    climate: "San Marcos is hot and noticeably humid. Winters are mild, with occasional freezes that still shut down neglected heat.",
    responseNote: "San Marcos is a southern route with Kyle, not a side trip from Georgetown.",
    nearby: ["kyle", "buda"],
    issues: [
      {
        title: "Systems that cool the thermostat and leave the air damp",
        body: "Short-cycling equipment does not dehumidify. In San Marcos that feels like a failed air conditioner even when the supply air is cold.",
        tags: ["cooling", "air", "install"],
      },
      {
        title: "Rental equipment with no maintenance record",
        body: "We write down what we find: failed parts, unsafe heat exchangers, and simple neglect. Owners can act on a list.",
        tags: ["maintenance", "heating"],
      },
      {
        title: "Drain and closet problems in smaller homes",
        body: "Air handlers in closets overflow into the house when the trap is wrong. That is a common San Marcos call after a heavy cooling week.",
        tags: ["cooling", "maintenance"],
      },
    ],
  },
  {
    slug: "lakeway",
    name: "Lakeway",
    region: "austin",
    county: "Travis",
    neighborhoods: ["Rough Hollow", "The Hills", "Lakeway Highlands"],
    zips: ["78734"],
    signature: "Lakeway’s multi-level homes and large glass areas need zoning or multiple systems done carefully.",
    intro: "Lakeway houses are larger, more glazed, and more likely to have several systems or zones. A single unhappy room in Rough Hollow or The Hills is not a reason to replace every unit. Access can be difficult, condensate has a long way to fall, and the afternoon sun on west glass is a real load.",
    housing: "Custom and semi-custom homes with multiple attic or closet systems. Equipment is often tucked where it looked good on a plan and works poorly for service.",
    climate: "Hill Country sun, a long cooling season, and mild winters that still include a freeze every few years.",
    responseNote: "Lakeway is routed with Bee Cave and west Austin.",
    nearby: ["bee-cave", "austin", "dripping-springs", "cedar-park"],
    issues: [
      {
        title: "Glass and levels the thermostat cannot see",
        body: "A Lakeway great room with west glass will not track a sensor in a hallway. Zoning or a dedicated system has to match how the house is actually used.",
        tags: ["cooling", "install", "ducts"],
      },
      {
        title: "Condensate that fails on a long drop",
        body: "Multi-story drains clog, lose their trap, or dump where nobody looks until the ceiling stains. We treat drainage as part of the repair, not a footnote.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Several systems, one of them failing",
        body: "We label which equipment serves which floor before replacing parts. Lakeway houses punish a guess.",
        tags: ["heating", "maintenance"],
      },
    ],
  },
  {
    slug: "bee-cave",
    name: "Bee Cave",
    region: "austin",
    county: "Travis",
    neighborhoods: ["Falconhead", "Spanish Oaks", "Lake Pointe"],
    zips: ["78738"],
    signature: "Bee Cave custom homes hide air handlers in tight spots, so access and drainage decide how a repair goes.",
    intro: "Falconhead, Spanish Oaks, and Lake Pointe are custom-home service. The equipment is often better than a production install and harder to reach. A coil that cannot be pulled, a drain that cannot be cleaned, or a condenser walled in by a finished yard turns a routine repair into a planning job. We look at access before we promise a same-day fix.",
    housing: "Multi-system custom homes, some with zoning, some with equipment in finished closets or low attics.",
    climate: "Western Travis County is sunny and hot, with enough elevation change that upstairs lofts overheat first.",
    responseNote: "Bee Cave is scheduled with Lakeway and west Austin.",
    nearby: ["lakeway", "austin", "dripping-springs"],
    issues: [
      {
        title: "Equipment installed where it cannot be serviced",
        body: "If we cannot pull a coil or reach a drain cleanly, we will say that before starting a repair that has to be abandoned halfway.",
        tags: ["maintenance", "install", "cooling"],
      },
      {
        title: "Lofts and bonus rooms that overheat",
        body: "A Bee Cave loft over a garage is a tough room. Duct corrections or a small ductless head are often more honest than another ton on the main system.",
        tags: ["cooling", "ducts", "install"],
      },
      {
        title: "High-end filtration added onto leaky returns",
        body: "A media cabinet does very little if the return is pulling attic air around it. We fix the leak first.",
        tags: ["air"],
      },
    ],
  },
  {
    slug: "dripping-springs",
    name: "Dripping Springs",
    region: "austin",
    county: "Hays",
    neighborhoods: ["Belterra", "Caliterra", "Headwaters", "Downtown"],
    zips: ["78620"],
    signature: "Many Dripping Springs homes heat with a heat pump, so winter backup is part of the job.",
    intro: "Dripping Springs is larger-lot Hill Country housing, much of it all-electric. Belterra, Caliterra, and Headwaters have real square footage, long duct runs, and heat pumps that carry both seasons. Downtown is smaller and older. A gas-furnace recommendation copied from Dallas is often the wrong starting point here.",
    housing: "Heat pumps, sometimes with electric backup, in attic or closet installations. Houses are spread out, so arrival windows need a realistic drive.",
    climate: "Days are hot and nights can drop harder than in central Austin. A heat pump has to be set up for both.",
    responseNote: "Dripping Springs is a west-and-south route with Bee Cave, not an add-on to a Kyle list unless the day is built that way.",
    nearby: ["bee-cave", "lakeway", "buda", "austin"],
    issues: [
      {
        title: "Heat pumps doing all of the winter work",
        body: "We check defrost, backup heat, and the outdoor unit’s condition before heating season. Dripping Springs homeowners feel a heat-pump failure immediately because there is often no gas furnace behind it.",
        tags: ["heating", "maintenance"],
      },
      {
        title: "Long drives and long duct runs",
        body: "Larger lots still have attic flex that is too long. The far bedroom complaint is familiar, and we measure it.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "New custom installs that skipped commissioning",
        body: "Charge, airflow, and thermostat configuration are not optional on a Hill Country house with a lot of glass. We commission what the original install left unfinished.",
        tags: ["install", "cooling"],
      },
    ],
  },
  {
    slug: "manor",
    name: "Manor",
    region: "austin",
    county: "Travis",
    neighborhoods: ["ShadowGlen", "Lagos", "Presidential Meadows", "Downtown Manor"],
    zips: ["78653"],
    signature: "Manor’s new construction often still falls under a builder warranty, and homeowners are not always told what that covers.",
    intro: "East of Austin, Manor is one of the faster-growing affordable new-home markets. ShadowGlen and the newer sections are full of builder HVAC. Some of it is still under warranty. Some of it was never installed carefully. We help you see which problems are warranty conversations and which are ordinary repairs you should just get done.",
    housing: "Production homes, attic flex, condensers on small side yards. Older downtown Manor is a much smaller part of the work.",
    climate: "Manor sits on open prairie east of Austin. Systems run in full sun with less tree cover than central neighborhoods.",
    responseNote: "Manor is routed with East Austin and Pflugerville.",
    nearby: ["austin", "pflugerville", "hutto", "round-rock"],
    issues: [
      {
        title: "Builder-warranty questions",
        body: "A failed part in year two may belong to the builder. We document model, serial, and the failure so you are not guessing when you call them. If the warranty will not cover it, we price the repair.",
        tags: ["install", "cooling", "maintenance"],
      },
      {
        title: "Undersized returns in production homes",
        body: "The blower is loud and the rooms are uneven. That pattern in Manor is usually the return and the flex, not a mysterious refrigerant leak.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "Heat strips carrying the winter",
        body: "New all-electric homes default to expensive backup heat when the heat pump is locked out or misconfigured. We check the settings, not just the thermostat batteries.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "hutto",
    name: "Hutto",
    region: "austin",
    county: "Williamson",
    neighborhoods: ["Star Ranch", "Emory Crossing", "Downtown Hutto"],
    zips: ["78634"],
    signature: "Hutto subdivisions are full of builder-grade condensers sitting on the hot side of the house.",
    intro: "Hutto’s growth looks like the rest of northeast Williamson County: new HOA neighborhoods, builder equipment, and houses that are only a few years into their first system. Star Ranch and Emory Crossing produce the same calls we see in Pflugerville — airflow, drainage, and outdoor units baking in the sun. Downtown Hutto is older and quieter.",
    housing: "New two-story production homes with attic systems. Limited side yards mean condensers are often jammed against a fence on the west side.",
    climate: "Hutto is hot, open, and a little colder in winter than south Austin.",
    responseNote: "Hutto is scheduled with Round Rock and Pflugerville.",
    nearby: ["round-rock", "pflugerville", "georgetown", "manor"],
    issues: [
      {
        title: "Condensers in trapped afternoon sun",
        body: "A unit between the house and a fence on the west side runs hotter and fails electrical parts sooner. We will tell you when placement is part of the problem and when a repair is still the right first step.",
        tags: ["cooling", "install"],
      },
      {
        title: "Builder ductwork in houses that are still new",
        body: "Age is not proof of a good install. Hutto homes from the last few years still need airflow checked when rooms are uneven.",
        tags: ["ducts", "cooling", "maintenance"],
      },
      {
        title: "Heat pump configuration left on factory defaults",
        body: "Lockout temperatures and backup-heat settings that were never adjusted make winter bills ugly. That is a setup visit, not a new system.",
        tags: ["heating"],
      },
    ],
  },
];
