import type { City } from "@/content/types";

export const dallasCities: City[] = [
  {
    slug: "dallas",
    name: "Dallas",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Lakewood", "East Dallas", "Preston Hollow", "Oak Cliff", "Uptown", "Lake Highlands", "Kessler Park"],
    zips: ["75214", "75206", "75225", "75208", "75219", "75230"],
    signature: "A lot of Dallas equipment sits in vented attics that run far hotter than the air outside.",
    intro: "Dallas homes ask a system to cool through long, humid afternoons and then heat on short notice when a front comes through. The houses themselves are just as mixed: bungalows in East Dallas, ranches in Lake Highlands, larger two-stories in Preston Hollow, and older duct runs in Oak Cliff.",
    housing: "Many Dallas systems and their ductwork live in unconditioned attics. Additions and closed-in porches often changed the cooling load without a matching change to the equipment.",
    climate: "Summer afternoons regularly push past 100°F, and a January night can still drop into the 20s.",
    responseNote: "Dallas requests are scheduled by neighborhood so a Lakewood visit and a North Dallas visit are not treated as the same drive.",
    nearby: ["irving", "richardson", "garland", "plano", "grand-prairie", "mesquite"],
    issues: [
      {
        title: "Attic systems that run all day and still miss the upstairs",
        body: "When flex duct in a Dallas attic is crushed, loose, or disconnected, the equipment can be fine and the rooms still will not settle. We check temperature drop and static pressure before we talk about a new condenser.",
        tags: ["cooling", "ducts"],
      },
      {
        title: "Furnaces that fail on the first real cold night",
        body: "A Dallas furnace can sit idle from April to November. The first hard front exposes cracked igniters, dirty flame sensors, and heat exchangers that should have been looked at in the fall.",
        tags: ["heating"],
      },
      {
        title: "Replacements that were matched to the old unit, not the house",
        body: "A like-for-like swap repeats the original sizing mistake. Dallas additions, new windows, and closed vents all change the load, so a replacement starts with the house as it is now.",
        tags: ["install", "air"],
      },
    ],
  },
  {
    slug: "fort-worth",
    name: "Fort Worth",
    region: "dallas",
    county: "Tarrant",
    neighborhoods: ["Fairmount", "Cultural District", "Tanglewood", "Ridglea", "Alliance", "Monticello"],
    zips: ["76107", "76109", "76116", "76131", "76102", "76110"],
    signature: "Fort Worth splits between older central houses and newer north-side homes that were built in a hurry.",
    intro: "A Fairmount bungalow and a house in Alliance do not have the same heating and cooling problem. Near the Cultural District we see original ductwork asked to carry a modern cooling load. Farther north, builder-grade systems from the last boom are reaching the age where capacitors, coils, and blower motors start to stack up.",
    housing: "Gas furnaces are still common across Tarrant County. Older central homes often have additions that were tied into ductwork never meant for them.",
    climate: "Fort Worth shares Dallas heat and adds a wide swing into hard freezes that stress heat pumps and idle furnaces alike.",
    responseNote: "We group Fort Worth visits so a west-side call and an Alliance call are scheduled with the drive in mind.",
    nearby: ["arlington", "lewisville", "denton", "flower-mound"],
    issues: [
      {
        title: "Older duct runs asked to cool houses that grew",
        body: "Porch conversions and rear additions in central Fort Worth often share a system that was sized for the original floor plan. Rooms at the end of the run are the ones that never catch up.",
        tags: ["cooling", "ducts"],
      },
      {
        title: "Heat that has not run since last winter",
        body: "Tarrant County freezes are not theoretical. Furnaces that were not checked in the fall fail on the night people actually need them, usually on a dirty sensor or a failing inducer.",
        tags: ["heating"],
      },
      {
        title: "Builder systems aging out together on the north side",
        body: "Neighborhoods built in the same few years have equipment aging in the same few years. The useful question is whether the system can be repaired safely or whether the coil and compressor are already at the end.",
        tags: ["install", "maintenance"],
      },
    ],
  },
  {
    slug: "arlington",
    name: "Arlington",
    region: "dallas",
    county: "Tarrant",
    neighborhoods: ["North Arlington", "Interlochen", "Lake Arlington", "South Arlington"],
    zips: ["76010", "76013", "76016", "76017", "76001"],
    signature: "Arlington’s large suburban houses spend a very long season at full cooling load.",
    intro: "Most Arlington calls are two-story homes from the 1980s through the 2000s. The equipment runs hard from May into October, and the upstairs is usually the complaint. We also work on small businesses around the entertainment corridor where a down system is a same-day problem, not a weekend inconvenience.",
    housing: "Long duct runs and a single return are common. Many systems have already had one compressor or condenser replaced without anyone sealing the ducts.",
    climate: "Arlington sits in the same hot, humid summer pattern as the rest of the Metroplex, with enough winter cold to matter for furnaces.",
    responseNote: "Arlington is scheduled with Grand Prairie and Fort Worth so we are not crossing the Metroplex twice in one morning.",
    nearby: ["fort-worth", "grand-prairie", "dallas", "irving"],
    issues: [
      {
        title: "Upstairs rooms that fall behind by midafternoon",
        body: "A system can make cold air and still lose the second floor if the returns are starved or the flex is kinked in the attic. We confirm that before recommending a larger unit.",
        tags: ["cooling", "ducts"],
      },
      {
        title: "Capacitors and contactors wearing out early",
        body: "Long Arlington runtimes are hard on electrical parts. A hot compressor that will not start is often a failed capacitor, and we carry common sizes so a simple failure does not wait on a parts house.",
        tags: ["cooling", "maintenance"],
      },
      {
        title: "Furnaces that short-cycle",
        body: "Dirty filters, failing flame sensors, and oversized equipment all show up as heat that starts and stops. We separate a control problem from a heat exchanger problem before anyone talks about replacement.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "plano",
    name: "Plano",
    region: "dallas",
    county: "Collin",
    neighborhoods: ["West Plano", "East Plano", "Legacy", "Willow Bend"],
    zips: ["75023", "75024", "75025", "75074", "75093"],
    signature: "A large share of Plano systems installed during the building boom are hitting replacement age at the same time.",
    intro: "Plano is mostly two-story family houses, many with two systems, and a lot of that equipment was installed between the late 1990s and the early 2010s. West Plano homes are larger and often have a system that serves a difficult upstairs. East Plano houses are older and more likely to have original ductwork still in the attic.",
    housing: "Two-story plans with the air handler in a hot attic are the default. Closed upstairs vents, meant to push air downstairs, usually make the balance worse.",
    climate: "Collin County summers are long and bright, and winter nights are cold enough that a neglected furnace becomes obvious.",
    responseNote: "Plano visits are grouped with Allen, Richardson, and Frisco.",
    nearby: ["frisco", "allen", "richardson", "mckinney", "carrollton"],
    issues: [
      {
        title: "One system trying to keep two floors even",
        body: "If the upstairs thermostat is satisfied and the downstairs is cold, or the reverse, the fix is often zoning, duct corrections, or a second system — not a colder setpoint.",
        tags: ["cooling", "ducts", "install"],
      },
      {
        title: "Original equipment reaching the end together",
        body: "When the condenser, coil, and furnace were installed as a set 12 to 15 years ago, repairing one major failure can be the wrong spend. We will say when a repair is the better buy.",
        tags: ["install", "heating"],
      },
      {
        title: "Return-air problems that look like weak equipment",
        body: "Undersized returns are common in Plano houses of this era. The blower is loud, the filter collapses, and the coil freezes. More tons will not fix a starved return.",
        tags: ["air", "maintenance", "ducts"],
      },
    ],
  },
  {
    slug: "frisco",
    name: "Frisco",
    region: "dallas",
    county: "Collin",
    neighborhoods: ["Phillips Creek Ranch", "Starwood", "Newman Village", "Richwoods"],
    zips: ["75033", "75034", "75035", "75036"],
    signature: "Frisco’s growth left a lot of builder-grade condensers that start struggling before year ten.",
    intro: "Frisco houses are newer, larger, and often still on the equipment the builder installed. Some of those systems are under a builder warranty, and some are just past it. We help you tell the difference before anyone pays to replace a unit someone else should be covering.",
    housing: "Big floor plans, long flex-duct runs, and condensers parked on the south or west side of the house are typical. HOA rules sometimes limit where equipment can move.",
    climate: "Open North Texas exposure means full sun on the condenser and attic temperatures that punish mediocre installs.",
    responseNote: "Frisco is scheduled with Plano, McKinney, and Little Elm-side Lewisville routes.",
    nearby: ["plano", "mckinney", "allen", "lewisville", "flower-mound"],
    issues: [
      {
        title: "Builder installs with kinked flex and missing returns",
        body: "A new Frisco house can cool poorly because the ductwork was rushed, not because the brand is wrong. We document what we find so a warranty conversation has something behind it.",
        tags: ["install", "ducts", "cooling"],
      },
      {
        title: "Equipment aging out just after the warranty",
        body: "Coils and compressors from the same building phase fail in a cluster. We will repair a single failed part when the rest of the system has years left.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Heat pumps and furnaces mixed across the same street",
        body: "Some Frisco sections are all-electric and some still have gas furnaces. Winter recommendations are not interchangeable, especially on the coldest nights.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "irving",
    name: "Irving",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Las Colinas", "Valley Ranch", "Heritage District", "Hackberry Creek"],
    zips: ["75038", "75039", "75061", "75063"],
    signature: "Irving mixes tight Las Colinas mechanical closets with older Valley Ranch houses.",
    intro: "A townhome in Las Colinas and a Valley Ranch single-family house need different service. Closets are cramped, condensate lines are easy to trap, and HOA rules can limit condenser changes. Valley Ranch and the Heritage side bring aging 1990s systems and ductwork that has never been sealed.",
    housing: "Multi-family and townhome equipment often shares access constraints that a typical attic install does not. Single-family homes farther north look more like the rest of Dallas.",
    climate: "Irving gets the full Metroplex summer and the same occasional hard freeze.",
    responseNote: "Irving sits between Dallas and Grand Prairie on the schedule, which keeps arrival windows tighter.",
    nearby: ["dallas", "grand-prairie", "carrollton", "arlington", "richardson"],
    issues: [
      {
        title: "Closet air handlers that are hard to service",
        body: "If the air handler was installed with no room to pull the coil, a ‘simple’ cleaning becomes a bigger job. We look at access before we quote a repair that cannot actually be done.",
        tags: ["maintenance", "cooling", "air"],
      },
      {
        title: "Condensate problems in tight builds",
        body: "Las Colinas closets and second-floor air handlers overflow when the trap or float switch is wrong. That leak often shows up before the cooling complaint does.",
        tags: ["cooling", "install"],
      },
      {
        title: "Aging Valley Ranch furnaces and coils",
        body: "Houses from the original Valley Ranch build are past the first replacement cycle. We separate a failed blower motor from a system that should be retired.",
        tags: ["heating", "install"],
      },
    ],
  },
  {
    slug: "mckinney",
    name: "McKinney",
    region: "dallas",
    county: "Collin",
    neighborhoods: ["Historic Downtown", "Stonebridge Ranch", "Craig Ranch", "Trinity Falls"],
    zips: ["75069", "75070", "75071", "75072"],
    signature: "Downtown McKinney houses and the master-planned sections north and west of the square are different trades.",
    intro: "Historic homes near the square often have no practical way to add a full duct system without tearing the house apart. Stonebridge Ranch, Craig Ranch, and Trinity Falls are conventional suburban systems, many of them builder-grade and now old enough to need real maintenance or a first replacement.",
    housing: "Expect ductless retrofits downtown and attic systems everywhere else. Some older houses still have obsolete equipment that should not be patched along.",
    climate: "McKinney is far enough north that winter nights are a real design condition, not an afterthought.",
    responseNote: "McKinney is routed with Frisco and Allen.",
    nearby: ["frisco", "allen", "plano"],
    issues: [
      {
        title: "Historic houses that should not get a forced-duct retrofit",
        body: "Ductless heads, carefully placed, often solve a downtown McKinney house without building bulkheads through original rooms. We will say so when that is the cleaner project.",
        tags: ["install", "cooling", "heating"],
      },
      {
        title: "Suburban systems with upstairs complaints",
        body: "Stonebridge and Craig Ranch two-stories lose the top floor when the duct design is lazy. We measure before we sell a second system you may not need.",
        tags: ["cooling", "ducts"],
      },
      {
        title: "Furnaces overlooked because the cooling gets all the attention",
        body: "Collin County heat makes summer the busy season, so heat exchangers and flue parts wait until the first freeze. A fall check is the cheaper version of that night.",
        tags: ["heating", "maintenance"],
      },
    ],
  },
  {
    slug: "garland",
    name: "Garland",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Downtown Garland", "Firewheel", "Springpark", "Embree"],
    zips: ["75040", "75041", "75042", "75044"],
    signature: "Garland’s housing stock is older, and a lot of the ductwork is original even when the equipment is not.",
    intro: "Garland is full of mid-century and 1970s–1980s ranches. Many have had the condenser replaced once, sometimes with a low-bid match, while the furnace, coil, and ducts stayed put. The useful repair is often airflow and the failed part, not a full system speech.",
    housing: "Original ductwork, package units on some roofs, and equipment in tight side yards are all common. Firewheel is newer than the core of town.",
    climate: "Garland shares Dallas heat and the same winter snaps that catch idle furnaces.",
    responseNote: "Garland is grouped with Mesquite, Richardson, and East Dallas.",
    nearby: ["mesquite", "richardson", "dallas", "plano"],
    issues: [
      {
        title: "New outdoor units on old, leaky ducts",
        body: "Replacing only the condenser in a Garland ranch feels cheaper until the attic ducts throw away the capacity you just bought. We look at both before recommending either.",
        tags: ["ducts", "cooling", "install"],
      },
      {
        title: "Practical repairs on older equipment",
        body: "If the furnace is safe and the coil is sound, a blower motor or capacitor is the right job. We will not talk you into a system to fix a part.",
        tags: ["maintenance", "heating"],
      },
      {
        title: "Airflow restrictions that freeze the coil",
        body: "Flat filters in undersized racks, collapsed flex, and closed supplies all show up as a system that ices over on a 98° day. The ice is a symptom.",
        tags: ["air", "cooling"],
      },
    ],
  },
  {
    slug: "grand-prairie",
    name: "Grand Prairie",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["North Grand Prairie", "South Grand Prairie", "Mira Lagos"],
    zips: ["75050", "75051", "75052", "75054"],
    signature: "Grand Prairie houses often have long duct runs and equipment that bakes beside a hot garage.",
    intro: "Grand Prairie stretches between Dallas and Fort Worth, and the houses follow that spread: older neighborhoods to the north and east, newer sections such as Mira Lagos to the south. Long flex runs and attic or garage-adjacent equipment lose a lot of cooling before the air reaches the last bedroom.",
    housing: "Single-story ranches and newer two-stories sit side by side depending on the section. Some roofs still carry package units.",
    climate: "The city gets full Metroplex sun with very little relief in July and August.",
    responseNote: "Grand Prairie is scheduled with Arlington and Irving.",
    nearby: ["arlington", "irving", "dallas"],
    issues: [
      {
        title: "Long flex runs that never quite reach the back rooms",
        body: "If the supply at the end of a Grand Prairie house is several degrees warmer than the supply near the air handler, the duct run is the problem. We measure that instead of guessing.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "Package units and split systems in the same neighborhood",
        body: "A rooftop package unit is a different repair from a split system behind the garage. We identify the equipment on the call so the truck shows up with a realistic plan.",
        tags: ["cooling", "heating", "maintenance"],
      },
      {
        title: "Systems that were never commissioned",
        body: "Newer sections sometimes have charge, airflow, or drain issues left over from the original install. A maintenance visit that only changes the filter will not catch them.",
        tags: ["install", "maintenance"],
      },
    ],
  },
  {
    slug: "richardson",
    name: "Richardson",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Canyon Creek", "Heights Park", "Berkner", "West Richardson"],
    zips: ["75080", "75081", "75082"],
    signature: "Richardson’s established neighborhoods hide aging attic systems under mature trees.",
    intro: "Richardson is not a new-construction market. Canyon Creek, the Berkner area, and the neighborhoods west of Central are full of 1970s–1990s houses with equipment that has already been replaced once. Cottonwood and oak debris also plug condenser coils, so a ‘weak system’ is sometimes a dirty one.",
    housing: "Two-story plans and original attic ducts are typical. Some houses have had room additions tied into the nearest supply.",
    climate: "Richardson matches Dallas summer heat, with tree cover that shades some condensers and dumps debris on the rest.",
    responseNote: "Richardson is routed with Plano, Garland, and North Dallas.",
    nearby: ["plano", "garland", "dallas", "carrollton"],
    issues: [
      {
        title: "Condenser coils packed with tree debris",
        body: "A Richardson condenser under pecans or cottonwoods can lose capacity while the indoor side looks fine. Cleaning the outdoor coil is a maintenance item, not a replacement conversation.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Additions served by the original system",
        body: "A sunroom or extra bedroom tied into a nearby supply rarely gets the air the rest of the house gets. We trace the run before we blame the compressor.",
        tags: ["ducts", "cooling", "install"],
      },
      {
        title: "Furnaces from the same era as the original cooling",
        body: "If the furnace stayed when the condenser was swapped, it may be 20 years older than the outdoor unit. Age alone is not a failure, but a cracked heat exchanger is not a part we patch.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "carrollton",
    name: "Carrollton",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Old Downtown", "Castle Hills", "Indian Creek", "Hebron"],
    zips: ["75006", "75007", "75010"],
    signature: "Carrollton’s older core and the newer north side fail in different ways.",
    intro: "Downtown Carrollton and the streets around it have older houses, older furnaces, and ductwork that has been repaired in pieces. North Carrollton and Hebron look like the rest of the Collin County growth: newer two-stories, builder equipment, and upstairs complaints. We do both, and we do not use the same recommendation for both.",
    housing: "Expect a mix of slab ranches and attic-ducted two-stories. Castle Hills brings larger homes with more than one system.",
    climate: "Carrollton gets Metroplex heat and enough winter cold for gas heat to matter.",
    responseNote: "Carrollton is scheduled with Lewisville, Plano, and Farmers Branch-side Dallas calls.",
    nearby: ["lewisville", "plano", "irving", "dallas", "flower-mound"],
    issues: [
      {
        title: "Older furnaces beside newer condensers",
        body: "The outdoor unit gets replaced when it dies in July. The furnace waits. In Carrollton’s older sections that mismatch is common, and the next failure is often heat, not cooling.",
        tags: ["heating", "install"],
      },
      {
        title: "North-side builder ductwork",
        body: "Hebron-area houses can have the same kinked flex and single-return limits we see in Frisco and Plano. Airflow testing tells us whether the equipment is actually the problem.",
        tags: ["ducts", "cooling", "install"],
      },
      {
        title: "Maintenance skipped because the system is ‘not that old’",
        body: "A seven-year-old system with a collapsed filter and a packed coil behaves like a failing one. Maintenance is the repair that keeps a real repair from happening in August.",
        tags: ["maintenance", "air"],
      },
    ],
  },
  {
    slug: "denton",
    name: "Denton",
    region: "dallas",
    county: "Denton",
    neighborhoods: ["Downtown Denton", "Robson Ranch", "Southridge"],
    zips: ["76201", "76205", "76207", "76208", "76210"],
    signature: "Denton combines older houses near downtown, campus rentals, and newer homes on the south and west sides.",
    intro: "Owner-occupied houses and rentals need different conversations. Near campus we see deferred maintenance and equipment that has been reset instead of repaired. Robson Ranch and the south side bring newer systems, some of them heat pumps, in houses that still see hard freezes.",
    housing: "Older pier-and-beam and bungalow stock sits near downtown. Suburban sections are conventional attic systems.",
    climate: "Denton is humid in summer and genuinely cold in winter compared with cities farther south in the Metroplex. Outdoor units and heat pumps need a freeze plan.",
    responseNote: "Denton is routed with Lewisville and Flower Mound, not with a Dallas morning.",
    nearby: ["lewisville", "flower-mound", "fort-worth", "frisco"],
    issues: [
      {
        title: "Deferred maintenance on rental systems",
        body: "Filters, drains, and capacitors get skipped until the system stops. We document what failed and what is simply worn so an owner can decide.",
        tags: ["maintenance", "cooling"],
      },
      {
        title: "Heat pumps on nights that actually freeze",
        body: "A heat pump sized only for mild weather will lean on backup heat during a Denton cold snap. We check the backup strips or gas furnace before winter, not during it.",
        tags: ["heating"],
      },
      {
        title: "Humidity complaints that are not a thermostat problem",
        body: "Oversized equipment short-cycles, cools the air, and leaves the house clammy. A bigger system is the wrong direction.",
        tags: ["air", "cooling", "install"],
      },
    ],
  },
  {
    slug: "allen",
    name: "Allen",
    region: "dallas",
    county: "Collin",
    neighborhoods: ["Watters Creek", "Twin Creeks", "Star Creek", "Montgomery Farm"],
    zips: ["75002", "75013"],
    signature: "Allen’s two-story houses are known for upstairs bedrooms that fall behind in the afternoon.",
    intro: "Allen is a family-suburb market: two-story plans, a system in the attic, and a thermostat on the first floor that says the house is fine while the kids’ rooms are not. Twin Creeks, Star Creek, and the neighborhoods around Watters Creek all produce the same pattern when the ducts or the returns are wrong.",
    housing: "Most homes have at least one attic system. Larger plans may have two. Builder-grade equipment from the 2000s is now in replacement range.",
    climate: "Allen gets full Collin County sun and a real winter, so both the coil and the furnace earn their keep.",
    responseNote: "Allen is grouped with Plano and McKinney.",
    nearby: ["plano", "mckinney", "frisco", "richardson"],
    issues: [
      {
        title: "A satisfied downstairs thermostat and a hot upstairs",
        body: "The sensor is doing its job on the floor where it lives. Allen upstairs problems are usually ducts, returns, or a missing second system, and we test those before selling tonnage.",
        tags: ["cooling", "ducts"],
      },
      {
        title: "Equipment from the 2000s reaching the end",
        body: "Major parts failures on 15-year-old matched systems deserve an honest repair-versus-replace conversation, with prices before any work.",
        tags: ["install", "maintenance"],
      },
      {
        title: "Heat checks that get skipped",
        body: "Because Allen cooling runs so long, furnaces are an afterthought. Flame sensors, drains on high-efficiency units, and flue issues show up on the first cold week.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "mesquite",
    name: "Mesquite",
    region: "dallas",
    county: "Dallas",
    neighborhoods: ["Town East", "Lucas Farms", "Falcon's Lair"],
    zips: ["75149", "75150", "75181"],
    signature: "Mesquite homeowners usually want the repair that solves the problem, not a replacement speech.",
    intro: "A lot of Mesquite housing dates from the 1970s through the 1990s, especially around Town East. Systems have been repaired over the years, sometimes well and sometimes with whatever part was cheapest. We start with what failed, what is still sound, and what it will cost to get reliable cooling or heat back.",
    housing: "Ranches and older two-stories with attic ducts are the norm. Some package units remain on roofs and backyards.",
    climate: "Mesquite shares Dallas summer heat. Winters are mild until they are not.",
    responseNote: "Mesquite is scheduled with Garland and East Dallas.",
    nearby: ["garland", "dallas", "richardson"],
    issues: [
      {
        title: "Repeat repairs on the same aging system",
        body: "A third major part in two years is a different decision from a capacitor. We will show you that history if you have it, and we will not invent urgency if you do not.",
        tags: ["maintenance", "cooling", "heating"],
      },
      {
        title: "Ducts that have never been sealed",
        body: "Original Mesquite ductwork often leaks into the attic. Conditioned air lost up there is capacity you already paid for.",
        tags: ["ducts", "cooling"],
      },
      {
        title: "Indoor air complaints in older houses",
        body: "Dust from a leaky return in the attic gets blamed on the filter brand. Sealing the return and confirming the filter size matters more than a thicker filter the rack cannot hold.",
        tags: ["air"],
      },
    ],
  },
  {
    slug: "lewisville",
    name: "Lewisville",
    region: "dallas",
    county: "Denton",
    neighborhoods: ["Castle Hills", "Timber Creek", "Old Town", "Valley Vista"],
    zips: ["75056", "75057", "75067", "75077"],
    signature: "Humidity near Lewisville Lake makes a house feel off even when the thermostat reads 74.",
    intro: "Lewisville ranges from older homes near Old Town to larger Castle Hills houses and newer sections to the west. Coils that are dirty or oversized short-cycle, drop the temperature, and leave the humidity in the room. People describe it as ‘the air conditioner works but the house feels sticky.’",
    housing: "Attic systems are common. Larger homes often have two units, and only one of them is the complaint.",
    climate: "Lake-adjacent humidity plus North Texas heat is the summer story. Winter freezes still reach Denton County.",
    responseNote: "Lewisville is routed with Flower Mound, Carrollton, and Denton.",
    nearby: ["flower-mound", "carrollton", "denton", "frisco", "irving"],
    issues: [
      {
        title: "Sticky houses at a normal thermostat setting",
        body: "If the system is short-cycling, the coil never stays cold long enough to pull moisture out. We check sizing, charge, and airflow instead of telling you to set it lower.",
        tags: ["cooling", "air"],
      },
      {
        title: "One of two systems down",
        body: "Castle Hills and similar sections often have more than one unit. We identify which system serves the rooms you care about before replacing parts on the healthy one.",
        tags: ["maintenance", "install"],
      },
      {
        title: "Winter backup that has not been tested",
        body: "Heat pumps around Lewisville need a working backup when a front blows through. We test it on purpose, not on the coldest night of the year.",
        tags: ["heating"],
      },
    ],
  },
  {
    slug: "flower-mound",
    name: "Flower Mound",
    region: "dallas",
    county: "Denton",
    neighborhoods: ["Bridlewood", "Wellington", "Canyon Falls", "Lakeside"],
    zips: ["75022", "75028"],
    signature: "Many Flower Mound homes have two or three systems, and the wrong one gets blamed first.",
    intro: "Flower Mound houses are larger than the Metroplex average. Bridlewood, Wellington, and Canyon Falls plans often have multiple attic systems, long duct runs, and a single room that never matches the thermostat. Replacing ‘the unit’ only works if it is the unit that serves that room.",
    housing: "Multi-system, two-story houses with equipment in hot attics are the usual job. Some homes have zoning that was added later and never set up correctly.",
    climate: "Flower Mound gets Denton County heat and real winter cold, so every system in the house has a cooling and a heating job.",
    responseNote: "Flower Mound is scheduled with Lewisville and Highland Village-side routes, not as a Dallas add-on.",
    nearby: ["lewisville", "denton", "carrollton", "frisco"],
    issues: [
      {
        title: "The thermostat that does not control the hot room",
        body: "We map which system feeds which rooms before we diagnose. A lot of Flower Mound ‘no cool’ calls are the upstairs unit, while the downstairs unit is running normally.",
        tags: ["cooling", "maintenance"],
      },
      {
        title: "Zoning that fights itself",
        body: "Aftermarket zone boards with no bypass, or dampers stuck open, create noise and rooms that will not settle. The equipment may be fine.",
        tags: ["ducts", "install"],
      },
      {
        title: "High-efficiency furnaces with neglected drains",
        body: "Condensate problems on a furnace show up as no heat, a tripped switch, or water at the air handler. That is a different failure from a bad igniter, and it is usually cheaper.",
        tags: ["heating"],
      },
    ],
  },
];
